import { useEffect, useState } from "react";
import { decideApproval } from "../api/client.js";

const STUB_PROPOSAL_ID = "stub-proposal-1";

export default function Approvals() {
  const [proposal, setProposal] = useState(null);
  const [note, setNote] = useState("");
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    // S1 has no GET /api/proposals list yet -- the approvals endpoint is
    // POST-only (it records a decision). We show the one fixture proposal
    // so the page has something real to act on.
    setProposal({
      id: STUB_PROPOSAL_ID,
      tool: "noop",
      rationale: "S1 stub proposal -- no real proposals are generated yet.",
      status: "pending",
    });
  }, []);

  async function decide(decision) {
    setBusy(true);
    setError(null);
    try {
      const resp = await decideApproval(STUB_PROPOSAL_ID, decision, note || null);
      setProposal(resp.proposal);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <section>
      <h2>Approvals</h2>
      <p className="hint">
        S1 stub: proposals aren't generated by the graph yet (see
        graph/nodes.py: propose_action). This page exercises the real
        POST /api/approvals/&#123;proposal_id&#125; endpoint against one
        fixture proposal.
      </p>

      {error && <p className="error">Error: {error}</p>}

      {proposal && (
        <div className="card">
          <p>
            <strong>Tool:</strong> {proposal.tool}
          </p>
          <p>
            <strong>Rationale:</strong> {proposal.rationale}
          </p>
          <p>
            <strong>Status:</strong> {proposal.status}
          </p>
          <textarea
            placeholder="Optional note"
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
          <div className="row">
            <button disabled={busy} onClick={() => decide("approve")}>
              Approve
            </button>
            <button disabled={busy} onClick={() => decide("deny")}>
              Deny
            </button>
          </div>
        </div>
      )}
    </section>
  );
}
